import type { Payment } from '@/lib/types'
import { ago } from './_time'

/** Demo settlement rate used for the MYR → USDC leg. Displayed wherever both appear. */
export const MYR_PER_USDC = 4.77

export function toUsdc(myr: number): number {
  return Math.round((myr / MYR_PER_USDC) * 100) / 100
}

const SUI_METHOD = 'Sui · USDC (sponsored)' as const

/**
 * Payments exist only for claims that reached `approved` or beyond. `pay_006` is
 * deliberately left in `failed` so the retry path in the insurer UI is walkable.
 * Manulife Insurance Berhad is the payer on every seeded payment.
 */
export const payments: Payment[] = [
  {
    id: 'pay_001',
    paymentReference: 'PAY-2026-0041',
    claimId: 'clm_001',
    claimNumber: 'CLM-2026-0041',
    payerId: 'org_manulife',
    payerName: 'Manulife Insurance Berhad',
    payeeId: 'org_gleneagles',
    payeeName: 'Gleneagles Kuala Lumpur — Manulife Panel Provider',
    patientName: 'Nurul Aisyah binti Rahman',
    amount: 11_900,
    currency: 'MYR',
    amountUsdc: toUsdc(11_900),
    status: 'completed',
    method: SUI_METHOD,
    createdAt: ago(46),
    initiatedAt: ago(45, 2),
    settledAt: ago(45),
    failureReason: null,
    transactionId: 'bc_003',
  },
  {
    id: 'pay_002',
    paymentReference: 'PAY-2026-0085',
    claimId: 'clm_003',
    claimNumber: 'CLM-2026-0085',
    payerId: 'org_manulife',
    payerName: 'Manulife Insurance Berhad',
    payeeId: 'org_mediassist',
    payeeName: 'MediAssist Medical Centre — Manulife Panel Provider',
    patientName: 'Rajesh Kumar a/l Subramaniam',
    amount: 3_350,
    currency: 'MYR',
    amountUsdc: toUsdc(3_350),
    status: 'pending',
    method: SUI_METHOD,
    createdAt: ago(6, 3),
    initiatedAt: null,
    settledAt: null,
    failureReason: null,
    transactionId: null,
  },
  {
    id: 'pay_003',
    paymentReference: 'PAY-2026-0063',
    claimId: 'clm_006',
    claimNumber: 'CLM-2026-0063',
    payerId: 'org_manulife',
    payerName: 'Manulife Insurance Berhad',
    payeeId: 'org_gleneagles',
    payeeName: 'Gleneagles Kuala Lumpur — Manulife Panel Provider',
    patientName: 'Nurul Aisyah binti Rahman',
    amount: 7_920,
    currency: 'MYR',
    amountUsdc: toUsdc(7_920),
    status: 'pending',
    method: SUI_METHOD,
    createdAt: ago(17),
    initiatedAt: null,
    settledAt: null,
    failureReason: null,
    transactionId: null,
  },
  {
    id: 'pay_004',
    paymentReference: 'PAY-2026-0029',
    claimId: 'clm_008',
    claimNumber: 'CLM-2026-0029',
    payerId: 'org_manulife',
    payerName: 'Manulife Insurance Berhad',
    payeeId: 'org_gleneagles',
    payeeName: 'Gleneagles Kuala Lumpur — Manulife Panel Provider',
    patientName: 'Siti Nadia binti Hassan',
    amount: 27_000,
    currency: 'MYR',
    amountUsdc: toUsdc(27_000),
    status: 'completed',
    method: SUI_METHOD,
    createdAt: ago(60, 2),
    initiatedAt: ago(58, 3),
    settledAt: ago(58),
    failureReason: null,
    transactionId: 'bc_012',
  },
  {
    id: 'pay_005',
    paymentReference: 'PAY-2026-0012',
    claimId: 'clm_009',
    claimNumber: 'CLM-2026-0012',
    payerId: 'org_manulife',
    payerName: 'Manulife Insurance Berhad',
    payeeId: 'org_mediassist',
    payeeName: 'MediAssist Medical Centre — Manulife Panel Provider',
    patientName: 'Rajesh Kumar a/l Subramaniam',
    amount: 4_250,
    currency: 'MYR',
    amountUsdc: toUsdc(4_250),
    status: 'completed',
    method: SUI_METHOD,
    createdAt: ago(87, 3),
    initiatedAt: ago(85, 1),
    settledAt: ago(85),
    failureReason: null,
    transactionId: 'bc_013',
  },
  {
    id: 'pay_006',
    paymentReference: 'PAY-2026-0088',
    claimId: 'clm_012',
    claimNumber: 'CLM-2026-0088',
    payerId: 'org_manulife',
    payerName: 'Manulife Insurance Berhad',
    payeeId: 'org_gleneagles',
    payeeName: 'Gleneagles Kuala Lumpur — Manulife Panel Provider',
    patientName: 'Siti Nadia binti Hassan',
    amount: 2_160,
    currency: 'MYR',
    amountUsdc: toUsdc(2_160),
    status: 'failed',
    method: SUI_METHOD,
    createdAt: ago(8, 4),
    initiatedAt: ago(7, 2),
    settledAt: null,
    failureReason:
      'Sponsored transaction rejected: the gas sponsor object was locked by a concurrent transaction at checkpoint 42,918,003. Safe to retry.',
    transactionId: null,
  },
]
